### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by akhilcacharya** [ming08108/skiptube#1]
no code, doesn't work

**Comment by ming08108** [comment]
you are welcome to submit a pull request.

**Comment by akhilcacharya** [comment]
No thanks

**Comment by vapaavetehinen** [comment]
Closing

**Comment by peakay** [comment]
wait I think this is a relevant issue, ack if u think it is a relevant issue

**Comment by ming08108** [comment]
Fixed
